on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up Go'
        uses: actions/setup-go@v2
      - name: 'Install Cloud SDK'
        uses: google-github-actions/setup-gcloud@v0
      - name: 'Set up Cloud SDK'
        run: |
          gcloud beta services enable
          gcloud components install pubsub-emulator
          gcloud components update
      - name: 'Start Pub/Sub emulator'
        run: |
          gcloud beta emulators pubsub start --project=testproject
      - name: Run program
        env:
          PUBSUB_EMULATOR_HOST: '[::1]:8432'
        run: |
          go run main.go
