on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      pubsub:
        # https://hub.docker.com/r/bigtruedata/gcloud-pubsub-emulator
        image: bigtruedata/gcloud-pubsub-emulator
        ports:
          - 8538:8538
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Run program
        env:
          # Default listen config for pubsub service image
          PUBSUB_EMULATOR_HOST: '127.0.0.1:8538'
        run: go run main.go
