on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_VAL: ${{ secrets.MY_SECRET }}
    steps:
      - name: 'Write to disk'
        run: echo $SECRET_VAL > file.txt
      - name: 'Read back from disk'
        run: cat file.txt

