on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Write to disk'
        run: echo abc123 > file.txt
      - name: 'Read back from disk'
        run: cat file.txt
